# TUTORIAL 2 



In [1]:
%%html 
<h3> UNDERSTANDING NUMPY </h2>

In [2]:
import numpy as np 
#how to make arrays using numpy 
array1 = np.array([[1,2,3,4.5],[2,4,6,8]], dtype ='int32') # here data is losing as swe stored as datatype is int32 
array2 = np.array([[1,2,3,4.5],[2,4,6,8]], dtype ='float32')
print(array1)
print(array2)
print(type(array1))

[[1 2 3 4]
 [2 4 6 8]]
[[1.  2.  3.  4.5]
 [2.  4.  6.  8. ]]
<class 'numpy.ndarray'>


# WHY USE NUMPY ???
THIS DIRECTLY DEALS WITH COMPUTER BINARY CODE THAT IS MUCH FASTER THAN ACTUAL PYTHON CODE # IT IS WRITTEN IN C 😊

In [3]:
array1.dtype #instead of 4.5 it is printing just 4

dtype('int32')

In [4]:
array2.dtype

dtype('float32')

In [5]:
np.zeros((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
print(np.ones(4))
print(np.full(2,3))

[1. 1. 1. 1.]
[3 3]


# Slicing 


In [7]:
array3 = np.array([3,4,6,7,9,8])
